openapi: 3.0.0
info:
  version: 1.0.0
  title: Worx Better BE
tags:
  - name: app
    description: Endpoints for works-better mobile app
  - name: agent
    description: Endpoints for works-better agent
paths:
  "/status/latest":
    get:
      tags:
        - app
      summary: Get the latest status from the Worx mower
      operationId: getLatestStatus
      responses:
        "200":
          description: Status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
        "404":
          description: Status not found
    post:
      tags:
        - agent
      summary: Add latest status
      operationId: addLatestStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MowerStatus"
        required: true
      responses:
        "201":
          description: New status entry created
        "400":
          description: Bad request
  "/status/distinct":
    get:
      tags:
        - app
      summary: Get the last 10 distinct statuses from the Worx mower
      operationId: getLastDistinctStatuses
      responses:
        "200":
          description: Statuses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StatusResponse"
  "/query-log":
    get:
      tags:
        - app
      summary: Get the query history
      operationId: getQueryLog
      responses:
        "200":
          description: QueryLog
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/QueryLogDto"
        "404":
          description: QueryLogs not found
    post:
      tags:
        - agent
      summary: Add latest query log
      operationId: addQueryLog
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryLogDto"
        required: true
      responses:
        "201":
          description: New query log entry created
        "400":
          description: Bad request
servers:
  - url: http://52.29.34.99:8080/
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-APP-ID
  schemas:
    StatusResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        battery:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
        state:
          type: string
        workReq:
          type: string
        batteryChargerState:
          type: string
          description: "Possible states: idle, charging"
        distance:
          type: integer
          format: int64
        timestamp:
          type: string
          format: 'date-time'
    QueryLogDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        successful:
          type: boolean
        timestamp:
          type: string
          format: 'date-time'
    MowerStatus:
      type: object
      properties:
        perc_batt:
          type: string
        state:
          type: string
        workReq:
          type: string
        message:
          type: string
        batteryChargerState:
          type: string
        distance:
          type: integer
          format: int64
security:
  - appId: []
