application:
  appId: 123abc
  mainServerUrl: "http://localhost:8080"
  scheduleInterval: "0 * * * * ?"
  landroid:
    url: ""
    username: "admin"
    pin: ""
logging:
  level:
    ee.codehouse.worxbetter: debug
feign:
  client:
    config:
      default:
        loggerLevel: full
