spring:
  pid:
    file: ./${spring.application.name}.pid
  application:
    name: worxlandroid-agent
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8010
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
logging:
  level:
    ee.codehouse: ERROR

application:
  appId: ""
  mainServerUrl: "http://52.29.34.99:8080"
  scheduleInterval: "0 * * * * ?"
  landroid:
    url: ""
    username: "admin"
    pin: ""
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: logstash
      port: 5044
      queue-size: 512
