version: '3'
services:
  worxlandroid-agent:
    image: worxlandroid-agent
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
networks:
  default:
    external:
      name: worxlandroid_net
